-- Seed content data
INSERT INTO content (title, description, type, genre, platform, release_year, poster_url, average_rating, total_episodes) VALUES
('Stranger Things', 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.', 'SERIES', 'Sci-Fi', 'Netflix', 2016, 'https://image.tmdb.org/t/p/w500/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg', 8.7, 34),
('Breaking Bad', 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine to secure his family''s future.', 'SERIES', 'Drama', 'Netflix', 2008, 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg', 9.5, 62),
('The Witcher', 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.', 'SERIES', 'Fantasy', 'Netflix', 2019, 'https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg', 8.2, 24),
('The Mandalorian', 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.', 'SERIES', 'Sci-Fi', 'Disney+', 2019, 'https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg', 8.8, 24),
('Wednesday', 'Follows Wednesday Addams years as a student, when she attempts to master her emerging psychic ability, thwart a monstrous killing spree, and solve the mystery.', 'SERIES', 'Comedy', 'Netflix', 2022, 'https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg', 8.1, 8),
('The Boys', 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.', 'SERIES', 'Action', 'Amazon Prime', 2019, 'https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg', 8.7, 32),
('House of the Dragon', 'An internal succession war within House Targaryen at the height of its power, 172 years before the events of Game of Thrones.', 'SERIES', 'Fantasy', 'HBO Max', 2022, 'https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg', 8.4, 18),
('Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 'MOVIE', 'Sci-Fi', 'Netflix', 2010, 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEhniVolVNbcb.jpg', 8.8, NULL),
('The Dark Knight', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.', 'MOVIE', 'Action', 'HBO Max', 2008, 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgME1O5TCX.jpg', 9.0, NULL),
('Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'MOVIE', 'Sci-Fi', 'Amazon Prime', 2014, 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 8.7, NULL),
('Oppenheimer', 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.', 'MOVIE', 'Drama', 'Amazon Prime', 2023, 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', 8.5, NULL),
('Dune', 'A noble family becomes embroiled in a war for control over the galaxy''s most valuable asset while its heir becomes troubled by visions of a dark future.', 'MOVIE', 'Sci-Fi', 'HBO Max', 2021, 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg', 8.0, NULL),
('Spider-Man: Across the Spider-Verse', 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.', 'MOVIE', 'Action', 'Netflix', 2023, 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg', 8.7, NULL),
('The Bear', 'A young chef from the fine dining world returns to Chicago to run his family''s Italian beef sandwich shop.', 'SERIES', 'Drama', 'Hulu', 2022, 'https://image.tmdb.org/t/p/w500/sHFlSuFGEx8mAAlVfMi5inLvTPg.jpg', 8.6, 28),
('Succession', 'The Roy family is known for controlling the biggest media and entertainment company in the world, but their world changes when their father steps down.', 'SERIES', 'Drama', 'HBO Max', 2018, 'https://image.tmdb.org/t/p/w500/7HW47XbkNQ5fiwQFYGWdw9gs7LF.jpg', 8.8, 39);
